# Generated by Django 4.1.1 on 2022-09-29 17:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Resevation",
            new_name="Reservation",
        ),
    ]
