# Generated by Django 4.1.1 on 2022-09-29 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0002_rename_resevation_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation",
                to="flight.flight",
            ),
        ),
    ]
